name: MCRealTime
version: 1.7
main: net.viewdns.applecraft.Main
author: CrashKillerYT
authors: [AppleCraft Team]
website: http://applecraft.viewdns.net
description: This Plugin put the real time live in the minecraft time

commands: 
  info: 
    usage: /<command>
    description: You got news and status about this plugin
    permission: mcrealtime.info
  contact: 
    usage: /<command>
    description: Here you will find out my contact details
    permission: mcrealtime.contact
