name: MCRealTime
version: 2.3
main: net.viewdns.applecraft.Main
author: CrashKillerYT
authors: [AppleCraft Team]
website: http://applecraft.viewdns.net
description: This Plugin put the real time live in the minecraft time.

commands: 
  mcrealtime: 
    description: Main command. Type it to find more out.
