name: MCRealTime
version: 4.2
main: live.applecraft.Main
authors: [Gabriel M.]
website: https://www.applecraft.live
description: Real time synchronization with game time.

commands: 
  mcrealtime: 
    description: Main command. Type it to find more out.
